export const GET_ARTICLES = 'ARTICLES::GET_ARTICLES';
export const GET_ARTICLES_REQUEST = "ARTICLES::GET_ARTICLES_REQUEST";
export const GET_ARTICLES_SUCCESS = "ARTICLES::GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAILURE = "ARTICLES::GET_ARTICLES_FAILURE";

export const TOGGLE_FAVOURITES = 'ARTICLES::TOGGLE_FAVOURITES';